server:
  port : 8880

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: coach-service
          uri: http://localhost:8098
          predicates:
            - Path=/coach/**
        - id: team-service
          uri: http://localhost:8090
          predicates:
            - Path=/team/**
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true