
  spring:
    application:
      name: discovery

    config:
      import: optional:configserver:http//localhost:8888

  server:
    port: 8761

  eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: false
      fetch-registry: false
      serviceUrl:
        defaultZone: http://localhost:${server.port}/eureka/
