
  server :
    port : 8098

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  management :
    tracing :
      sampling :
        probability: 1.0

  spring:
    application:
      name: COACH-SERVICE
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/coach_db?createDatabaseIfNotExist=true
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: create
      database: MYSQL
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect